### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by bdenney** [learn-co-curriculum/python-p3-intro-to-class-attributes-and-methods#1]
### Canvas Link

https://learning.flatironschool.com/courses/6049/pages/intro-to-class-attributes-and-class-methods?module_item_id=439040

### Concern

Class methods and attributes are taught as a concept after already have been used in previous modules.

**Comment by professor-ben** [comment]
Hey Brandon,

I just reached out on Slack as well, but I wanted to check and see if there were any specific instances of this issue that you might have noticed outside of the first object inheritance lab.

Thanks,
Ben
