### ISSUE TITLE
Link goes to wrong site

### ISSUE THREAD

**Issue by ckesurf** [learn-co-curriculum/python-p3-intro-to-class-attributes-and-methods#3]
### Canvas Link

https://learning.flatironschool.com/courses/6049/pages/intro-to-class-attributes-and-class-methods?module_item_id=439040

### Concern

The `Classes - Python` at the bottom in `Resources` goes to the generic Python documentation site, as opposed to the specific section on Classes

**Comment by pgill97** [comment]
Added `https://docs.python.org/3/tutorial/classes.html` to the classes resource link.
